# -*- coding: utf-8 -*-
"""lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xhMuL7voDkqYxSAfkrQ4vrzus-kXpTA

# Lab2 REP
**# my name is sadain abbasi::**
"""

